services:
  backend:
    build: ./backend
    develop:
      watch:
        - action: sync+restart
          path: .
          target: /app
        - action: rebuild
          path: Dockerfile
        - action: rebuild
          path: poetry.lock
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@db:5432/boffin
      REDIS_URL: redis://redis:6379/0
      DEV_MODE: 1
      FORCE_COLOR: 1
      WEB_CONCURRENCY: 1  # sets the number of uvicorn workers
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:80/status/healthcheck"]
      interval: 5s
      timeout: 5s
      retries: 0

    ports:
      - "127.0.0.1:8000:80"
      - "127.0.0.1:5678:5678"

  db:
    image: postgres:16.0-alpine
    read_only: true
    security_opt:
      - no-new-privileges:true
    environment:
      POSTGRES_DB: boffin
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_run:/var/run/postgresql
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "127.0.0.1:5432:5432"

  redis:
    image: redis:7.2-alpine
    read_only: true
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "127.0.0.1:6379:6379"

volumes:
  db:
  db_run:
